app-db-backend = ""
halt-height = 0
halt-time = 0
iavl-cache-size = 1000
iavl-disable-fastnode = false
index-events = []
inter-block-cache = true
min-retain-blocks = 0
minimum-gas-prices = "0stake"
pruning = "custom"
pruning-interval = 100
pruning-keep-recent = 1000
query-gas-limit = "0"

[api]
address = "tcp://0.0.0.0:26650"
enable = true
enabled-unsafe-cors = true
max-open-connections = 1000
rpc-max-body-bytes = 1000000
rpc-read-timeout = 10
rpc-write-timeout = 0
swagger = true

[grpc]
address = "0.0.0.0:26649"
enable = true
max-recv-msg-size = "10485760"
max-send-msg-size = "2147483647"

[grpc-web]
enable = true

[mempool]
max-txs = -1

[state-sync]
snapshot-interval = 0
snapshot-keep-recent = 2

[streaming.abci]
keys = []
plugin = ""
stop-node-on-err = true

[telemetry]
datadog-hostname = ""
enable-hostname = false
enable-hostname-label = false
enable-service-label = false
enabled = false
global-labels = []
metrics-sink = ""
prometheus-retention-time = 0
service-name = ""
statsd-addr = ""

[wasm]
lru_size = 0
query_gas_limit = 300000
